//LOCALHOST
#############################################################################################
# LOCALHOST
#############################################################################################

// ***************************************************************************************
// PLAYER ROUTES
// ***************************************************************************************

### Error route
GET http://localhost:8080/abc_xyz
### Base Route
GET http://localhost:8080

### Get all players
GET http://localhost:8080/baseball-player

### Get player by ID
GET http://localhost:8080/baseball-player/6470d9ab0088d326752aeb15

### Create new player
POST http://localhost:8080/baseball-player HTTP/1.1
Content-Type: application/json

{
    "name": "Billy Bob",
    "age": 25,
    "hometown": "Paris, ID",
    "team": "New York Mets",
    "handedness": "S/R",
    "hrs": 55,
    "average": 0.280
}

### Update player by ID
PUT http://localhost:8080/baseball-player/6470d9ab0088d326752aeb15 HTTP/1.1
Content-Type: application/json

{
    "name": "Billy Shawn",
    "age": 27,
    "hometown": "Paris, TX",
    "team": "Milwaukee Brewers",
    "handedness": "S/R",
    "hrs": 85,
    "average": 0.290
}

### Delete player by ID
DELETE http://localhost:8080/baseball-player/64716bebc6d24865beecc112

// ***************************************************************************************
// TEAM ROUTES
// ***************************************************************************************

### Get all teams
GET http://localhost:8080/baseball-team

### Get team by ID
GET http://localhost:8080/baseball-team/647e8c86b1e1c62a33214cf2

### Create new team
POST http://localhost:8080/baseball-team HTTP/1.1
Content-Type: application/json

{
    "name": "Miami Marlins",
    "location": "Miami, FL",
    "stadium": "LoanDepot Park",
    "world_series_wins": 2
}

### Update team by ID
PUT http://localhost:8080/baseball-team/647e8c86b1e1c62a33214cf2 HTTP/1.1
Content-Type: application/json

{
    "name": "Philadelphia Phillies",
    "location": "Philadelphia, PA",
    "stadium": "Citizens Bank Park",
    "world_series_wins": 2
}

### Delete team by ID
DELETE http://localhost:8080/baseball-team/64811a71344f773c90151107

#############################################################################################
# PRODUCTION DISPLAY (render.com)
#############################################################################################

// ***************************************************************************************
// PLAYER ROUTES
// ***************************************************************************************
### Base Route
GET https://baseball-api.onrender.com/

### Get all players
GET https://baseball-api.onrender.com/baseball-player

### Get single player by ID
GET https://baseball-api.onrender.com/baseball-player/64728dc39bb04d8f1dfd177f

### Create new player
POST https://baseball-api.onrender.com/baseball-player HTTP/1.1
Content-Type: application/json

{
    "name": "Billy Bob",
    "age": 55,
    "hometown": "Paris, ID",
    "team": "Colorado Rockies",
    "handedness": "L/R",
    "hrs": "287",
    "average": ".280"
}

### Update player by ID
PUT https://baseball-api.onrender.com/baseball-player/64728dc39bb04d8f1dfd177f HTTP/1.1
Content-Type: application/json

{
    "name": "Billy Bob",
    "age": 55,
    "hometown": "Paris, TX",
    "team": "Colorado Rockies",
    "handedness": "L/R",
    "hrs": 287,
    "average": 0.280
}

### Delete player by ID
DELETE https://baseball-api.onrender.com/baseball-player/647293e19bb04d8f1dfd1782

// ***************************************************************************************
// TEAM ROUTES
// ***************************************************************************************

### Get all teams
GET https://baseball-api.onrender.com/baseball-team

### Get team by ID
GET https://baseball-api.onrender.com/baseball-team/64811d2efbc3093fc0557631

### Create new team
POST https://baseball-api.onrender.com/baseball-team HTTP/1.1
Content-Type: application/json

{
    "name": "Miami Marlins",
    "location": "Miami, FL",
    "stadium": "LoanDepot Park",
    "world_series_wins": 2
}

### Update team by ID
PUT https://baseball-api.onrender.com/baseball-team/64811d2efbc3093fc0557631 HTTP/1.1
Content-Type: application/json

{
    "name": "Miami Marlins",
    "location": "Miami, FL",
    "stadium": "LoanDepot Park",
    "world_series_wins": 2
}

### Delete team by ID
DELETE https://baseball-api.onrender.com/baseball-team/64811d2efbc3093fc0557631